# Site settings
baseurl = "https://vermontsoloretreat.org/"
languageCode = "en-us"
title = "Vermont Solo Retreat"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Your Name"
  description = "Your Description"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "your@mail.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    type = "hero"
    title = "Vermont Solo Retreat"
    description = "Visit Dorset, Vermont to practice meditation in beauty and serenity!"
    buttontext = "begin"
    picture = "dorset.jpg"
    
  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "Purpose"
    description = "We provide a secluded, quiet environment for practitioners to pursue a solo meditation and spiritual practice.  'Solo' means there is no resident teacher and the practitioner is entirely responsible for his/her schedule of practice. We believe that most retreat centers are far too expensive. Our cost is only $40 per person per day.  You may use the fully equiped kitchen to prepare your own meals or opt to have meals provided for an extra $50 per person per day.  Please note this retreat is a place for spiritual practice and philosophical reflection and is not intended for use as a vacation destination."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "dorset.jpg"

  [[params.block]]
    id = "accomdations"
    type = "text"
    title = "Accomodations"
    description = "The retreat house is a secluded 2 bedroom, 2 bathroom, 3 story, 2500 square foot house nestled in the forests of Dorset, Vermont.  The house has a fully equipped kitchen and internet access.  We can accomodate as many as four practitioners (one couple per bedroom)."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "dorset.jpg"
    
  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "Contact"
    description = "Please send email to vermontsoloretreat@gmail.com for more information and reservations.  We look forward to meeting you!"
    # the picture is stored at static/images/
    picture = "dorset.jpg"

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is stored at static/images/
#    picture = "pic04.jpg"

  # contact form
#  [[params.block]]
#    id = "contact"
#    type = "contact"
#    title = "Get in Touch"
#    picture = "pic05.jpg"

#    [params.block.form]
#      name = "Name"
#      email = "Your Email"
#      message = "Your Message"
#      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = false

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "fa-dribbble"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

  #    [[params.footer.copyright.notice]]
  #      text = "© Untitled"

   #   [[params.footer.copyright.notice]]
   #     text = "Design: [HTML5UP](//html5up.net)"

    #  [[params.footer.copyright.notice]]
    #    text = "Demo Images: [Unsplash](//unsplash.com/)"
